### ISSUE TITLE
Suggestion: the `for` snippet you might as well make `indexValue` a simple one: `1`

### ISSUE THREAD

**Issue by NevilleDNZ** [TrisTOON/language-algol60#4]
Suggestion: 

- In the `for` snippet you might as well make `indexValue` a simple zero: `0` (Update: now suggesting `1` ... see note below)
- For `by` make the default increment *one*: `1`
- You might want move the cursor past the `until` into the `max` field.

Update of Suggestion :
- in the `for` snippet you might as well make `indexValue` a simple one: `1` (Update!)

At the risk of perpetuating [dogma](https://www.cs.utexas.edu/users/EWD/transcriptions/EWD08xx/EWD831.html), and because algol60 actually allows a zero lower bound (update: but `Size` appears to use `lower bound` of ONE). 

Rational: I have none.  ... Even looking at the sample a60 code it seems split 50% / 50% between zero and one. (In the code sample I managed to hack in a bug)

However, strings are indexed from one... eg:
```
begin
  outchar(1,"ABCD",4)
end
```
Outputs a: "D"

regarding: AbsMax...

Tidied up sample AbsMax.a60 code ... [absmax_v00.txt](https://github.com/TrisTOON/language-algol60/files/4882878/absmax_v00.txt)

So I found Algol60 **arrays** indeed agnostic about the lower bound of any type array.  Sweet.  Moreover it FORCES the coder to define the lower bound every array declaration. eg `array x[1:99] ` **must** have a `lower bound:`  (i.e. it cannot default to either zero or one!)

FYI: Nice to see that Marst has extensive array bounds checking ... So clearly Marst sneaks then array bounds onto the stack somehow.

I'm guessing that this upper/lower bounds info (with checking) was not programmatically available to the classic Algol60 user.

**Comment by PolariTOON** [comment]
When i wrote the `for` and `range` snippets, i did indeed ask myself that question: what to suggest as an initial value for the loop?

As *for* loops and *while* loops share the same prefix in Algol 60, i didn't want to favor one type of loop more than another. So i chose to provide an agnostic suggestion and i added two smaller snippets:

- `range` (which produces `a step b until c`) and
- `test` (which produces `a while b`).

With them, all you need is to auto-complete two times to get the type of loop you want.

Then, why neither `1` nor `0` as a lower bound nor `1` as a step in the `range` snippet? I decided to propose no values and only variable names, since i though names would be more self-describing than values and for consistency with the rest of the snippets.

For now, i have no plans to replace `indexValue` in the `for` snippets with a number, but you convinced me that if i had to choose between `0` and `1`, i would chose `1` for consistency with `inchar`, `outchar` and `outstring`. (Forgive me Dijkstra...)

But ultimately, it's all matter of taste since, as you noted, there is no restrictions in Algol 60 on the bounds of arrays (apart from being an integer either positive or zero or negative).

To conclude: i prefer to let the user chose the right bound for the right use case.

I'll close this issue for now, but feel free to continue the discussion in this issue or even to reopen it if you want.
